spring.application.name=GetJob

spring.datasource.url=jdbc:postgresql://localhost:5432/jobfinder
spring.datasource.username=postgres
spring.datasource.password=badar512
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
jwt.secret=${JWT_SECRET:9f3c2d4e7a6b8c1d5e9f0a2b4c6d8e1f3a5b7c9d0e2f4a6b8c1d3e5f7a9b0c2d}
cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:8080,http://localhost:5173}
jsearch.api.key=${RAPID_API_KEY:b2d573306dmsh94f1e8659ce9dbcp1ed860jsn85deba6d519f}
jsearch.api.host=${JSEARCH_API_HOST:jsearch.p.rapidapi.com}
jsearch.api.url=https://jsearch.p.rapidapi.com/search
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.flyway.enabled=false