DROP PROCEDURE IF EXISTS public.archive_old_saved_jobs(INTEGER);
DROP FUNCTION IF EXISTS public.audit_application_changes();
DROP FUNCTION IF EXISTS public.ensure_event_timestamp();
DROP FUNCTION IF EXISTS public.sync_job_company();
DROP FUNCTION IF EXISTS public.touch_company_updated_at();

DROP TABLE IF EXISTS public.saved_jobs_archive;
DROP TABLE IF EXISTS public.application_audit;
DROP TABLE IF EXISTS public.saved_jobs;
DROP TABLE IF EXISTS public.applications;
DROP TABLE IF EXISTS public.job;
DROP TABLE IF EXISTS public.company;
DROP TABLE IF EXISTS public.users;

CREATE TABLE public.users (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	name character varying(100) NOT NULL,
	email character varying(100) NOT NULL,
	password_hash character varying(255) NOT NULL,
	role character varying(32) NOT NULL,
	created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.user_profile (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	user_id bigint NOT NULL UNIQUE,
	bio text,
	avatar_url text,
	linkedin_url text,
	phone character varying(20),
	website text,
	location character varying(150),
	created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.notifications (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	user_id bigint NOT NULL,
	message text NOT NULL,
	type character varying(32) NOT NULL,
	is_read boolean NOT NULL DEFAULT FALSE,
	created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT notifications_type_check CHECK ((type)::text = ANY (ARRAY['APPLICATION_UPDATE'::character varying, 'JOB_SAVED'::character varying, 'JOB_RECOMMENDED'::character varying, 'SYSTEM'::character varying]::text[]))
);

CREATE TABLE public.resume (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	user_id bigint NOT NULL,
	file_url text NOT NULL,
	file_name character varying(255),
	version integer NOT NULL DEFAULT 1,
	is_active boolean NOT NULL DEFAULT FALSE,
	uploaded_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.company (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	name character varying(150) NOT NULL,
	description text,
	location character varying(150),
	logo_url text,
	created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.job (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	title character varying(150) NOT NULL,
	location character varying(150),
	description text,
	salary_range character varying(50),
	type character varying(20) NOT NULL,
	apply_url text,
	source character varying(100),
	posted_at timestamp without time zone,
	created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
	company_name character varying(150) NOT NULL,
	company_id bigint NOT NULL
);

CREATE TABLE public.applications (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	user_id bigint NOT NULL,
	job_id bigint NOT NULL,
	resume_url text,
	applied_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.saved_jobs (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	user_id bigint NOT NULL,
	job_id bigint NOT NULL,
	saved_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.application_audit (
	audit_id bigint GENERATED BY DEFAULT AS IDENTITY,
	application_id bigint,
	user_id bigint,
	job_id bigint,
	action_type character varying(16) NOT NULL,
	action_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
	details text
);

CREATE TABLE public.saved_jobs_archive (
	archive_id bigint GENERATED BY DEFAULT AS IDENTITY,
	saved_job_id bigint NOT NULL,
	user_id bigint NOT NULL,
	job_id bigint NOT NULL,
	saved_at timestamp without time zone NOT NULL,
	archived_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
	archive_reason character varying(255) NOT NULL
);

ALTER TABLE public.users
	ADD CONSTRAINT users_pkey PRIMARY KEY (id),
	ADD CONSTRAINT users_email_key UNIQUE (email),
	ADD CONSTRAINT users_role_check CHECK ((role)::text = ANY (ARRAY['SOFTWARE_ENG'::character varying, 'AI_ENG'::character varying, 'DEVOPS'::character varying, 'ML'::character varying, 'CYBERSECURITY'::character varying, 'OTHER'::character varying]::text[]));

ALTER TABLE public.user_profile
	ADD CONSTRAINT user_profile_pkey PRIMARY KEY (id),
	ADD CONSTRAINT user_profile_user_key UNIQUE (user_id),
	ADD CONSTRAINT user_profile_user_fk FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE public.notifications
	ADD CONSTRAINT notifications_pkey PRIMARY KEY (id),
	ADD CONSTRAINT notifications_user_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE public.resume
	ADD CONSTRAINT resume_pkey PRIMARY KEY (id),
	ADD CONSTRAINT resume_user_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX ux_resume_one_active_per_user ON public.resume(user_id) WHERE is_active = TRUE;

CREATE INDEX idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX idx_notifications_created_at ON public.notifications(created_at DESC);
CREATE INDEX idx_resume_user_id ON public.resume(user_id);
CREATE INDEX idx_resume_uploaded_at ON public.resume(uploaded_at DESC);

CREATE OR REPLACE FUNCTION public.touch_user_profile_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	NEW.updated_at := CURRENT_TIMESTAMP;
	RETURN NEW;
END;
$$;

CREATE TRIGGER trg_user_profile_updated_at
BEFORE UPDATE ON public.user_profile
FOR EACH ROW
EXECUTE FUNCTION public.touch_user_profile_updated_at();

ALTER TABLE public.company
	ADD CONSTRAINT company_pkey PRIMARY KEY (id),
	ADD CONSTRAINT company_name_key UNIQUE (name);

ALTER TABLE public.job
	ADD CONSTRAINT job_pkey PRIMARY KEY (id),
	ADD CONSTRAINT job_company_fk FOREIGN KEY (company_id) REFERENCES public.company(id) ON DELETE CASCADE,
	ADD CONSTRAINT job_type_check CHECK ((type)::text = ANY (ARRAY['FULL_TIME'::character varying, 'PART_TIME'::character varying, 'INTERNSHIP'::character varying, 'CONTRACT'::character varying, 'FREELANCE'::character varying, 'ENTRY_LEVEL'::character varying, 'REMOTE'::character varying]::text[]));

ALTER TABLE public.applications
	ADD CONSTRAINT applications_pkey PRIMARY KEY (id),
	ADD CONSTRAINT applications_user_job_key UNIQUE (user_id, job_id),
	ADD CONSTRAINT applications_user_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
	ADD CONSTRAINT applications_job_fk FOREIGN KEY (job_id) REFERENCES public.job(id) ON DELETE CASCADE;

ALTER TABLE public.saved_jobs
	ADD CONSTRAINT saved_jobs_pkey PRIMARY KEY (id),
	ADD CONSTRAINT saved_jobs_user_job_key UNIQUE (user_id, job_id),
	ADD CONSTRAINT saved_jobs_user_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
	ADD CONSTRAINT saved_jobs_job_fk FOREIGN KEY (job_id) REFERENCES public.job(id) ON DELETE CASCADE;

ALTER TABLE public.application_audit
	ADD CONSTRAINT application_audit_pkey PRIMARY KEY (audit_id);

ALTER TABLE public.saved_jobs_archive
	ADD CONSTRAINT saved_jobs_archive_pkey PRIMARY KEY (archive_id),
	ADD CONSTRAINT saved_jobs_archive_saved_job_key UNIQUE (saved_job_id);

CREATE INDEX idx_job_company_id ON public.job(company_id);
CREATE INDEX idx_job_type ON public.job(type);
CREATE INDEX idx_job_created_at ON public.job(created_at DESC);
CREATE INDEX idx_applications_user_id ON public.applications(user_id);
CREATE INDEX idx_applications_job_id ON public.applications(job_id);
CREATE INDEX idx_applications_applied_at ON public.applications(applied_at DESC);
CREATE INDEX idx_saved_jobs_user_id ON public.saved_jobs(user_id);
CREATE INDEX idx_saved_jobs_job_id ON public.saved_jobs(job_id);
CREATE INDEX idx_saved_jobs_saved_at ON public.saved_jobs(saved_at DESC);
CREATE INDEX idx_application_audit_application_id ON public.application_audit(application_id);
CREATE INDEX idx_application_audit_action_at ON public.application_audit(action_at DESC);
CREATE INDEX idx_saved_jobs_archive_saved_at ON public.saved_jobs_archive(saved_at DESC);

CREATE OR REPLACE FUNCTION public.sync_job_company()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
	normalized_company_name character varying(150);
BEGIN
	normalized_company_name := NULLIF(btrim(COALESCE(NEW.company_name, '')), '');

	IF normalized_company_name IS NULL THEN
		normalized_company_name := 'Unspecified';
	END IF;

	NEW.company_name := normalized_company_name;

	SELECT c.id
	INTO NEW.company_id
	FROM public.company c
	WHERE c.name = normalized_company_name
	LIMIT 1;

	IF NEW.company_id IS NULL THEN
		INSERT INTO public.company (name)
		VALUES (normalized_company_name)
		RETURNING id INTO NEW.company_id;
	END IF;

	RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.ensure_event_timestamp()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	IF TG_TABLE_NAME = 'applications' THEN
		NEW.applied_at := COALESCE(NEW.applied_at, CURRENT_TIMESTAMP);
	ELSIF TG_TABLE_NAME = 'saved_jobs' THEN
		NEW.saved_at := COALESCE(NEW.saved_at, CURRENT_TIMESTAMP);
	END IF;

	RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.touch_company_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	NEW.updated_at := CURRENT_TIMESTAMP;
	RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_application_changes()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	IF TG_OP = 'INSERT' THEN
		INSERT INTO public.application_audit (application_id, user_id, job_id, action_type, details)
		VALUES (NEW.id, NEW.user_id, NEW.job_id, 'INSERT', 'Application created');
		RETURN NEW;
	ELSIF TG_OP = 'UPDATE' THEN
		INSERT INTO public.application_audit (application_id, user_id, job_id, action_type, details)
		VALUES (NEW.id, NEW.user_id, NEW.job_id, 'UPDATE', 'Application updated');
		RETURN NEW;
	ELSIF TG_OP = 'DELETE' THEN
		INSERT INTO public.application_audit (application_id, user_id, job_id, action_type, details)
		VALUES (OLD.id, OLD.user_id, OLD.job_id, 'DELETE', 'Application deleted');
		RETURN OLD;
	END IF;

	RETURN NULL;
END;
$$;

CREATE TRIGGER trg_company_updated_at
BEFORE UPDATE ON public.company
FOR EACH ROW
EXECUTE FUNCTION public.touch_company_updated_at();

CREATE TRIGGER trg_job_company_sync
BEFORE INSERT OR UPDATE ON public.job
FOR EACH ROW
EXECUTE FUNCTION public.sync_job_company();

CREATE TRIGGER trg_applications_timestamp
BEFORE INSERT ON public.applications
FOR EACH ROW
EXECUTE FUNCTION public.ensure_event_timestamp();

CREATE TRIGGER trg_saved_jobs_timestamp
BEFORE INSERT ON public.saved_jobs
FOR EACH ROW
EXECUTE FUNCTION public.ensure_event_timestamp();

CREATE TRIGGER trg_application_audit
AFTER INSERT OR UPDATE OR DELETE ON public.applications
FOR EACH ROW
EXECUTE FUNCTION public.audit_application_changes();

CREATE OR REPLACE PROCEDURE public.archive_old_saved_jobs(IN p_days integer DEFAULT 90)
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO public.saved_jobs_archive (saved_job_id, user_id, job_id, saved_at, archived_at, archive_reason)
	SELECT s.id, s.user_id, s.job_id, s.saved_at, CURRENT_TIMESTAMP, 'Older than ' || p_days || ' days'
	FROM public.saved_jobs s
	WHERE s.saved_at < CURRENT_TIMESTAMP - make_interval(days => p_days)
	ON CONFLICT (saved_job_id) DO UPDATE
		SET user_id = EXCLUDED.user_id,
			job_id = EXCLUDED.job_id,
			saved_at = EXCLUDED.saved_at,
			archived_at = EXCLUDED.archived_at,
			archive_reason = EXCLUDED.archive_reason;

	DELETE FROM public.saved_jobs
	WHERE saved_at < CURRENT_TIMESTAMP - make_interval(days => p_days);
END;
$$;

INSERT INTO public.users (name, email, password_hash, role, created_at) VALUES
	('Admin User', 'admin@getjob.local', '$2a$10$adminseedhashadminseedhashadminseedhashadminseedhash', 'OTHER', CURRENT_TIMESTAMP - INTERVAL '14 days'),
	('Ava Patel', 'ava.patel@getjob.local', '$2a$10$avaseedhashavaseedhashavaseedhashavaseedhashavaseedh', 'SOFTWARE_ENG', CURRENT_TIMESTAMP - INTERVAL '8 days'),
	('Noah Kim', 'noah.kim@getjob.local', '$2a$10$noahseedhashnoahseedhashnoahseedhashnoahseedhashnoah', 'DEVOPS', CURRENT_TIMESTAMP - INTERVAL '3 days');

INSERT INTO public.company (name, description, location, logo_url, created_at) VALUES
	('Acme Labs', 'Product engineering and hiring platform team.', 'Austin, TX', 'https://cdn.getjob.local/logos/acme.png', CURRENT_TIMESTAMP - INTERVAL '30 days'),
	('Vertex AI', 'Applied machine learning and model operations.', 'San Francisco, CA', 'https://cdn.getjob.local/logos/vertex.png', CURRENT_TIMESTAMP - INTERVAL '25 days'),
	('Cloud Harbor', 'Infrastructure tooling and platform reliability.', 'Remote', 'https://cdn.getjob.local/logos/cloudharbor.png', CURRENT_TIMESTAMP - INTERVAL '20 days');

INSERT INTO public.job (title, location, description, salary_range, type, apply_url, source, posted_at, created_at, company_name) VALUES
	('Backend Java Engineer', 'Austin, TX', 'Build Spring Boot services and PostgreSQL-backed APIs.', '$115k-$140k', 'FULL_TIME', 'https://jobs.acmelabs.local/backend-java-engineer', 'seed', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '5 days', 'Acme Labs'),
	('Machine Learning Engineer', 'San Francisco, CA', 'Ship model training pipelines and inference services.', '$130k-$165k', 'FULL_TIME', 'https://jobs.vertexai.local/ml-engineer', 'seed', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '4 days', 'Vertex AI'),
	('Platform DevOps Engineer', 'Remote', 'Own release pipelines, observability, and cloud infrastructure.', '$120k-$150k', 'FULL_TIME', 'https://jobs.cloudharbor.local/devops-engineer', 'seed', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '2 days', 'Cloud Harbor');

INSERT INTO public.applications (user_id, job_id, applied_at) VALUES
	((SELECT id FROM public.users WHERE email = 'ava.patel@getjob.local'), (SELECT id FROM public.job WHERE title = 'Backend Java Engineer' AND company_name = 'Acme Labs'), CURRENT_TIMESTAMP - INTERVAL '2 days'),
	((SELECT id FROM public.users WHERE email = 'noah.kim@getjob.local'), (SELECT id FROM public.job WHERE title = 'Platform DevOps Engineer' AND company_name = 'Cloud Harbor'), CURRENT_TIMESTAMP - INTERVAL '1 day');

INSERT INTO public.saved_jobs (user_id, job_id, saved_at) VALUES
	((SELECT id FROM public.users WHERE email = 'ava.patel@getjob.local'), (SELECT id FROM public.job WHERE title = 'Machine Learning Engineer' AND company_name = 'Vertex AI'), CURRENT_TIMESTAMP - INTERVAL '120 days'),
	((SELECT id FROM public.users WHERE email = 'ava.patel@getjob.local'), (SELECT id FROM public.job WHERE title = 'Platform DevOps Engineer' AND company_name = 'Cloud Harbor'), CURRENT_TIMESTAMP - INTERVAL '1 day');

CALL public.archive_old_saved_jobs(90);
